# Render.yaml configuration for VidFold backend
services:
  - type: web
    name: vidfold-backend
    env: python3
    runtime: python3
    buildCommand: pip install --no-cache-dir -r requirements.txt
    startCommand: uvicorn app.server:app --host 0.0.0.0 --port $PORT --log-level info --timeout-keep-alive 75
    rootDir: backend
    healthCheckPath: /
    healthCheckTimeout: 100
    autoDeploy: false
    envVars:
      - key: PORT
        value: "8000"
      - key: PYTHON_VERSION
        value: 3.11.0
      - key: PYTHONPATH
        value: /app
      - key: SUPABASE_URL
        sync: false
      - key: SUPABASE_KEY
        sync: false
      - key: SUPABASE_JWT_SECRET
        sync: false
      - key: HUGGINGFACE_API_KEY
        sync: false
      - key: OPENAI_API_KEY
        sync: false
      - key: ACCESS_TOKEN_EXPIRE_MINUTES
        value: "1440"
      - key: REFRESH_TOKEN_EXPIRE_MINUTES
        value: "43200"
      - key: YOUTUBE_API_KEY
        sync: false
      - key: UPSTASH_REDIS_HOST
        sync: false
      - key: UPSTASH_REDIS_PORT
        value: 6379
      - key: UPSTASH_REDIS_PASSWORD
        sync: false 