# Render.yaml configuration for VidFold backend
services:
  - type: web
    name: vidfold-backend
    env: docker
    rootDir: backend
    dockerfilePath: Dockerfile
    dockerCommand: bash -c "mkdir -p /var/lib/apt/lists/partial && chmod -R 777 /var/lib/apt/lists/partial && python -m uvicorn app.main:app --host 0.0.0.0 --port $PORT --log-level debug"
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
      - key: PYTHONPATH
        value: /app
      - key: SUPABASE_URL
        sync: false
      - key: SUPABASE_KEY
        sync: false
      - key: SUPABASE_JWT_SECRET
        sync: false
      - key: HUGGINGFACE_API_KEY
        sync: false
      - key: OPENAI_API_KEY
        sync: false
      - key: ACCESS_TOKEN_EXPIRE_MINUTES
        value: "1440"
      - key: REFRESH_TOKEN_EXPIRE_MINUTES
        value: "43200" 