# Render.yaml configuration for VidFold backend
services:
  - type: web
    name: vidfold-backend
    env: python3
    rootDir: backend  # Explicitly set the root directory
    buildCommand: |
      pip install -r requirements.txt
      sudo apt-get update
      sudo apt-get install -y ffmpeg
    startCommand: python3 -m uvicorn app.main:app --host 0.0.0.0 --port $PORT --log-level debug
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
      - key: PYTHONPATH
        value: /opt/render/project/src/backend
      - key: SUPABASE_URL
        sync: false
      - key: SUPABASE_KEY
        sync: false
      - key: SUPABASE_JWT_SECRET
        sync: false
      - key: HUGGINGFACE_API_KEY
        sync: false
      - key: OPENAI_API_KEY
        sync: false
      - key: ACCESS_TOKEN_EXPIRE_MINUTES
        value: "1440"
      - key: REFRESH_TOKEN_EXPIRE_MINUTES
        value: "43200" 