# Render.yaml configuration for VidFold backend
services:
  - type: web
    name: vidfold-backend
    env: python3
    buildCommand: |
      cd backend
      pip install -r requirements.txt
      apt-get update && apt-get install -y ffmpeg
    startCommand: |
      cd backend
      export PYTHONPATH=$PWD
      python -m uvicorn asgi:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
      - key: PYTHONPATH
        value: /opt/render/project/src/backend
      - key: SUPABASE_URL
        sync: false
      - key: SUPABASE_KEY
        sync: false
      - key: SUPABASE_JWT_SECRET
        sync: false
      - key: HUGGINGFACE_API_KEY
        sync: false
      - key: OPENAI_API_KEY
        sync: false
      - key: ACCESS_TOKEN_EXPIRE_MINUTES
        value: "1440"
      - key: REFRESH_TOKEN_EXPIRE_MINUTES
        value: "43200" 